# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb62ef83ff1da46cb6987b1f642f7313c2c2b730c07b30e3cf70609868731a001fffcc871b676993df8d0616ce01cd8d7ad9ec70eba3353018ce4030e93c960

test:
  secret_key_base: 69343a2458d7277d4172fc16c51ee04833649543c3724c3f43a498428abb31b3b2fcb582776481157be8ecad3cc3552069801ad99c0ce153773764b879f75914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
